Draw face
SyrupMG/tg-genclub-bot pull request #2
Opened 2024-09-10 21:03 UTC by illus0r

2024-09-10 23:34 UTC, sleeping-h approved these changes

2024-09-10 23:34 UTC, sleeping-h commented on bot/bot.py
> +    application.add_handler(CommandHandler("draw_circle", draw_face))
должно быть draw_face например

2024-09-10 23:36 UTC, sleeping-h requested changes
почему-то гитхаб решил, что с моей стороны аппрув, но это не так)

2024-09-11 06:08 UTC, abesmon commented
да, определенно это нужно исправить11 сент. 2024 г., в 02:34, Nadia ***@***.***> написал(а):﻿
@sleeping-h approved this pull request.



In bot/bot.py:
> @@ -84,6 +153,7 @@ def main():
     
     application.add_handler(CommandHandler("start", start))
     application.add_handler(CommandHandler("draw_circle", draw_circle))
+    application.add_handler(CommandHandler("draw_circle", draw_face))

должно быть draw_face например

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-09-11 07:35 UTC, abesmon requested changes
исправить нейминг команды

2024-09-11 13:09 UTC, illus0r commented
@abesmon пофиксил, вроде

2024-09-11 13:10 UTC, abesmon approved these changes

2024-09-11 13:10 UTC, merged